TASK-50921 : Add the app into the app center
Meeds-io/challenges pull request #1
Opened 2021-11-23 14:45 UTC by GouadriaHanen

2021-11-23 16:06 UTC, Rdidmohamedelhadi requested changes

2021-11-23 16:06 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/resources/locale/navigation/portal/global_en.properties
> +# Copyright (C) 2020 Meeds Association
```suggestion
# Copyright (C) 2021 Meeds Association
```

2021-11-23 16:06 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/WEB-INF/conf/challenges/app-center-configuration.xml
> +Copyright (C) 2020 Meeds Association
```suggestion
Copyright (C) 2021 Meeds Association
```

2021-11-23 16:06 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/WEB-INF/conf/challenges/bundle-configuration.xml
> +Copyright (C) 2020 Meeds Association
```suggestion
Copyright (C) 2021 Meeds Association
```

2021-11-23 16:06 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/WEB-INF/conf/challenges/dynamic-container-configuration.xml
> +Copyright (C) 2020 Meeds Association
```suggestion
Copyright (C) 2021 Meeds Association
```

2021-11-23 16:06 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/WEB-INF/conf/challenges/portal-configuration.xml
> +Copyright (C) 2020 Meeds Association
```suggestion
Copyright (C) 2021 Meeds Association
```

2021-11-23 16:06 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/WEB-INF/conf/challenges/portal/portal/global/navigation.xml
> +Copyright (C) 2020 Meeds Association
```suggestion
Copyright (C) 2021 Meeds Association
```

2021-11-23 16:06 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/WEB-INF/conf/challenges/portal/portal/global/pages.xml
> +Copyright (C) 2020 Meeds Association
```suggestion
Copyright (C) 2021 Meeds Association
```

2021-11-23 16:08 UTC, Rdidmohamedelhadi submitted a review, later dismissed
see that https://community.exoplatform.com/portal/dw/activity?id=370023
  **https://www.gnu.org/licenses/gpl-howto.en.html
  https://www.gnu.org/licenses/why-not-lgpl.en.html**

2021-11-23 19:31 UTC, ahamdi requested changes

2021-11-23 19:31 UTC, ahamdi commented on challenges-webapp/src/main/webapp/WEB-INF/conf/challenges/bundle-configuration.xml
> +
Line to remove

2021-11-23 19:31 UTC, ahamdi commented on challenges-webapp/src/main/webapp/WEB-INF/conf/challenges/bundle-configuration.xml
> +          </values-param>
Fix indentation please

2021-11-23 19:31 UTC, ahamdi commented on challenges-webapp/src/main/webapp/WEB-INF/conf/challenges/bundle-configuration.xml
> +                <value>locale.portlet.Challenges</value>
Is it needed to add both resource bundles in all bundle configurations

2021-11-24 20:45 UTC, ahamdi approved these changes

2021-11-25 08:36 UTC, merged