Edit challenge
Meeds-io/challenges pull request #13
Opened 2021-12-14 12:19 UTC by GouadriaHanen

2021-12-15 10:39 UTC, Rdidmohamedelhadi requested changes, later dismissed

2021-12-15 10:39 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/resources/locale/portlet/Challenges_en.properties
> +
delete this please !!

2021-12-15 10:39 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/ChallengeAssignment.vue
>        menuId: `AssigneeMenu${parseInt(Math.random() * 10000).toString()}`,
```suggestion
      menuId: `AssigneeMenu${parseInt(Math.random() * 10000)}`,
```

2021-12-15 10:39 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/ChallengesList.vue
> +          <challenge-card :challenge="challenge" @edit="emitEditChallenge($event)" />
```suggestion
          <challenge-card :challenge="challenge" @edit="this.$emit('edit-challenge',challenge);" />
```

2021-12-15 10:39 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/ChallengesList.vue
>    }
```suggestion
  }
  }
```

2021-12-15 10:39 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/ChallengeDrawer.vue
> +        });
change this  in saveChallenge function please

2021-12-15 10:39 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/ChallengeDatePicker.vue
> +    }
```suggestion
    getFormatDate(date) {
      const lang = eXo.env.portal.language;
      const options = { month: 'long' };
      const day = String(date.getDate());
      const year = String(date.getFullYear());
      return `${date.toLocaleDateString(lang || 'en', options)} ${day}, ${year}` ;
    }
```

2021-12-15 16:31 UTC, ahamdi commented on challenges-webapp/src/main/webapp/vue-app/challenges/challengesUtils.js
> +  return `${date.toLocaleDateString(lang || 'en', options)} ${day}, ${year}` ;
Please consider languages with country variant like pt8BR or es_ES

2021-12-16 10:57 UTC, ahamdi approved these changes

2021-12-16 11:08 UTC, merged