add announcement services
Meeds-io/challenges pull request #16
Opened 2021-12-20 14:36 UTC by GouadriaHanen

2021-12-20 15:45 UTC, Rdidmohamedelhadi requested changes

2021-12-20 15:45 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/dao/AnnouncementDAO.java
> +  public List<AnnouncementEntity> findAllAnnouncementByChallenge( Long challengeId,int offset, int limit) {
```suggestion
  public List<AnnouncementEntity> findAllAnnouncementByChallenge(Long challengeId, int offset, int limit) {
```

2021-12-20 15:45 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/service/AnnouncementServiceImpl.java
> +  public static final String   ACTIVITY_DEFAULT_IMAGE        = "/challenges/images/challengesAppIcon.png";
```suggestion
  public static final String                 ANNOUNCEMENT_ACTIVITY_TYPE     = "exo-announcement:activity";

  public static final String                 ACTIVITY_DEFAULT_IMAGE        = "/challenges/images/challengesAppIcon.png";
```

2021-12-20 15:45 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/service/AnnouncementServiceImpl.java
> +    }
just use challengeId for Model announcement

2021-12-20 15:45 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/service/AnnouncementServiceImpl.java
> +    }
Challenge ch
```suggestion
    Challenge challenge = announcement.getChallenge();
    if (challenge == null) {
      throw new ObjectNotFoundException("challenge does not exist");
    }
```

2021-12-20 15:45 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/service/AnnouncementServiceImpl.java
> +    IdentityManager identityManager = CommonsUtils.getService(IdentityManager.class);
use class Utils please

2021-12-20 15:45 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/service/AnnouncementServiceImpl.java
> +    Identity owner = identityManager.getOrCreateIdentity("space",space.getPrettyName());
update this org.exoplatform.challenges.utils.Utils#getIdentityByTypeAndId please and  you can use it

2021-12-20 15:45 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/service/AnnouncementServiceImpl.java
> +    Map<String, String>  params = new LinkedHashMap();
```suggestion
   Map<String, String> params = new HashMap<>();
```

2021-12-20 15:45 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/service/AnnouncementServiceImpl.java
> +    ((Map)params).put("announcementDescription", announcement.getChallenge().getDescription());
delete parse Map please

2021-12-20 15:45 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/storage/AnnouncementStorage.java
> +  public List<AnnouncementEntity> findAllAnnouncementByChallenge(Long challengeId,int offset, int limit) {
```suggestion
  public List<AnnouncementEntity> findAllAnnouncementByChallenge(Long challengeId, int offset, int limit) {
```

2021-12-20 15:45 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/storage/AnnouncementStorage.java
> +    return announcementDAO.findAllAnnouncementByChallenge(challengeId,offset, limit);
```suggestion
    return announcementDAO.findAllAnnouncementByChallenge(challengeId, offset, limit);
```

2021-12-20 15:45 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/utils/EntityMapper.java
> +    AnnouncementStorage announcementStorage = CommonsUtils.getService(AnnouncementStorage.class);
why did you change that

2021-12-20 16:32 UTC, Rdidmohamedelhadi requested changes, later dismissed

2021-12-20 16:32 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/utils/EntityMapper.java
> +    return new ChallengeRestEntity(challenge.getId(),challenge.getTitle(),challenge.getDescription(),Utils.getSpaceById(String.valueOf(challenge.getAudience())), challenge.getStartDate(), challenge.g
change this in the input and do not use limit

2021-12-20 16:32 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/utils/Utils.java
> +  }
you need to update the getUsers method that already exists in utils

2021-12-20 16:32 UTC, Rdidmohamedelhadi commented on challenges-api/src/main/java/org/exoplatform/challenges/service/AnnouncementService.java
> +  Announcement createAnnouncement(Announcement announcement) throws IllegalAccessException, ObjectNotFoundException;
```suggestion
  Announcement createAnnouncement(Announcement announcement, String username) throws IllegalAccessException, ObjectNotFoundException;
```

2021-12-20 16:32 UTC, Rdidmohamedelhadi commented on challenges-api/src/main/java/org/exoplatform/challenges/service/AnnouncementService.java
> +   * @return created {@link Announcement} with generated technical identifier
```suggestion
   * @param announcement {@link Announcement} object to create
   * @param username User name accessing announcement
   * @return created {@link Announcement} with generated technical identifier
```

2021-12-20 16:32 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/java/org/exoplatform/challenges/service/AnnouncementServiceImpl.java
> +    if ( assignee == null) {
```suggestion
    if ( assignee.isEmpty()) {
```

2021-12-20 19:52 UTC, ahamdi requested changes

2021-12-20 19:52 UTC, ahamdi commented on challenges-api/src/main/java/org/exoplatform/challenges/service/ChallengeService.java
> +  ChallengeRestEntity createChallenge(Challenge challenge, String username) throws IllegalAccessException;
We should not use the Rest entity here, let it be just on Rest services layer. In services layer we use DTOs that could be used to create Rest entities on upper layer.
We can have a new class Rest Entity Builder that will be used just for building Rest responses.

2021-12-20 19:52 UTC, ahamdi commented on challenges-services/src/main/java/org/exoplatform/challenges/service/AnnouncementServiceImpl.java
> +  private ExoSocialActivity createActivity(Announcement announcement) {
Could you put this in a Listener ?

2021-12-20 19:52 UTC, ahamdi commented on challenges-services/src/main/java/org/exoplatform/challenges/service/ChallengeServiceImpl.java
> +  public ChallengeRestEntity createChallenge(Challenge challenge, String username) throws IllegalAccessException {
The same as for Announcements, we need to let the Rest entity be in the Rest services layer.

2021-12-21 18:23 UTC, ahamdi commented on challenges-services/src/main/java/org/exoplatform/challenges/listener/NewAnnouncementActivityGenerator.java
> +  public static final String ANNOUNCEMENT_ACTIVITY_TYPE = "exo-announcement:activity";
challenges-announcement
```suggestion
  public static final String ANNOUNCEMENT_ACTIVITY_TYPE = "challenges-announcement";
```

2021-12-21 18:24 UTC, ahamdi commented on challenges-services/src/main/java/org/exoplatform/challenges/listener/NewAnnouncementActivityGenerator.java
> +public class NewAnnouncementActivityGenerator extends Listener<AnnouncementStorage, Announcement> {
No need for the word New in the class name

2021-12-21 18:25 UTC, ahamdi commented on challenges-services/src/main/java/org/exoplatform/challenges/listener/NewAnnouncementActivityGenerator.java
> +    activity = activityStorage.saveActivity(owner, activity);
this line should go in the createActivity function

2021-12-21 18:39 UTC, ahamdi requested changes

2021-12-21 18:39 UTC, ahamdi commented on challenges-services/src/main/java/org/exoplatform/challenges/listener/NewAnnouncementActivityGenerator.java
> +
We should not create HTML rendering inside Java functions, you can pass the needed information to the front where you can get the avatar URL and the user full name.
You can use this service already available as in  : https://github.com/Meeds-io/social/blob/develop/webapp/portlet/src/main/webapp/vue-apps/common/js/UserService.js

2021-12-21 18:39 UTC, ahamdi commented on challenges-services/src/main/java/org/exoplatform/challenges/rest/AnnouncementRest.java
> +    }
Please move this check to the service layer

2021-12-21 18:39 UTC, ahamdi commented on challenges-services/src/main/java/org/exoplatform/challenges/rest/ChallengeRest.java
> +      List<Announcement>  announcementList = announcementService.findAllAnnouncementByChallenge(challengeId,0,0);
Could you add the offset and limit as parameters with default values if they arfe missing

2021-12-21 18:39 UTC, ahamdi commented on challenges-services/src/main/java/org/exoplatform/challenges/rest/ChallengeRest.java
> +      return Response.ok(EntityMapper.fromChallenge(challenge,announcementList)).build();
Why do you return the full list ?

2021-12-21 18:43 UTC, ahamdi commented on challenges-services/src/main/java/org/exoplatform/challenges/listener/NewAnnouncementActivityGenerator.java
> +    announcementStorage.saveAnnouncement(announcement);
We need to surround this call with a RequestLifecycle.begin() and RequestLifecycle.end()

2021-12-22 17:53 UTC, ahamdi approved these changes

2021-12-22 17:58 UTC, merged