Tasks-51729 ~ 51730 : Add Entity of Challenge and Announcement
Meeds-io/challenges pull request #2
Opened 2021-11-25 18:57 UTC by Rdidmohamedelhadi

2021-11-25 20:44 UTC, ahamdi requested changes

2021-11-25 20:44 UTC, ahamdi commented on challenges-services/src/main/resources/db/changelog/challenge-rdbms.db.changelog-1.0.0.xml
> +    <changeSet author="agenda" id="1.0.0-0" dbms="oracle,postgresql">
```suggestion
    <changeSet author="challenge" id="1.0.0-0" dbms="oracle,postgresql">
```

2021-11-25 20:44 UTC, ahamdi commented on challenges-services/src/main/resources/db/changelog/challenge-rdbms.db.changelog-1.0.0.xml
> +            <column name="TITLE" type="VARCHAR(200)">
We need to validate the length with @mzorai for the title and the description

2021-11-25 20:44 UTC, ahamdi commented on challenges-services/src/main/resources/db/changelog/challenge-rdbms.db.changelog-1.0.0.xml
> +            <column name="COMMENT" type="VARCHAR(200)"/>
@mzorai Could you precise the maximum length for this ?

2021-11-25 22:04 UTC, Rdidmohamedelhadi commented on challenges-services/src/main/resources/db/changelog/challenge-rdbms.db.changelog-1.0.0.xml
> +    <changeSet author="agenda" id="1.0.0-0" dbms="oracle,postgresql">
Done !!

2021-11-29 13:39 UTC, ahamdi approved these changes
LGTM

2021-11-29 14:14 UTC, merged