TASK-51210 :  First screen of the App
Meeds-io/challenges pull request #5
Opened 2021-12-02 14:06 UTC by GouadriaHanen

2021-12-02 17:13 UTC, ahamdi requested changes

2021-12-02 17:13 UTC, ahamdi commented on challenges-api/src/main/java/org/exoplatform/challenges/services/ChallengeService.java
> +    boolean canAddChallenge( String currentUser) throws Exception;
```suggestion
    boolean canAddChallenge(String currentUser) throws Exception;
```

2021-12-02 17:13 UTC, ahamdi commented on challenges-services/src/main/java/org/exoplatform/challenges/services/ChallengeServiceImpl.java
> +        this.organizationService = organizationService;
Do we really need the organizationService ?

2021-12-02 17:34 UTC, Rdidmohamedelhadi requested changes

2021-12-02 17:34 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/vue-app/challenges/challengesServices.js
> +    return resp;
```suggestion
          if (resp && resp.ok) {
        return resp.json();
      } else {
        throw new Error('Server indicates an error while sending request');
      }
```

2021-12-02 17:34 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/AddChallenge.vue
> +        {{ $t('exoplatform.challenges.button.addChallenge') }}
It's better to always use simple keys for labels:
exoplatform.challenges.button.addChallenge = > challenges.button.addChallenge

2021-12-02 17:34 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/WelcomeMessage.vue
> +      loading="lazy">
please add alt

2021-12-02 17:34 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/WelcomeMessage.vue
> +      <p v-else> {{ $t('exoplatform.challenges.message.welcomeMessageForUser') }} </p>
exoplatform.challenges.message.welcomeMessage ==>challenges.welcomeMessage
exoplatform.challenges.message.welcomeMessageForManager==>challenges.welcomeMessageForManager
exoplatform.challenges.message.welcomeMessageForManager==>challenges.welcomeMessageForManager

2021-12-02 17:34 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/Challenges.vue
> +        can-add-challenge="canAddChallenge" />
```suggestion
        :can-add-challenge="canAddChallenge" />
```

2021-12-03 09:17 UTC, Rdidmohamedelhadi requested changes

2021-12-03 09:17 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/resources/locale/portlet/Challenges_en.properties
> +challenges.message.welcomeMessageForUser=There is not yet challenges, stay tuned they will be added!
challenges.message.welcomeMessage ==>challenges.welcomeMessageForUser
challenges.message.welcomeMessageForManager ==> challenges.welcomeMessageForManager
challenges.message.welcomeMessageForUser==> challenges.welcomeMessageForUser

2021-12-03 09:17 UTC, Rdidmohamedelhadi commented on challenges-webapp/src/main/webapp/vue-app/challenges/components/WelcomeMessage.vue
> +      alt="challenges"
please add description for this img and use i18n

You can see more details here : https://www.semrush.com/blog/alt-text/

2021-12-06 19:55 UTC, ahamdi requested changes

2021-12-06 19:55 UTC, ahamdi commented on challenges-webapp/src/main/webapp/vue-app/challenges/challengesServices.js
> +      'Content-Type': 'application/json'
Isn't it plain/text ?

2021-12-07 12:35 UTC, GouadriaHanen commented on challenges-webapp/src/main/webapp/vue-app/challenges/challengesServices.js
> +      'Content-Type': 'application/json'
done!

2021-12-07 13:27 UTC, ahamdi approved these changes
LGTM

2021-12-07 13:40 UTC, Rdidmohamedelhadi approved these changes

2021-12-07 13:41 UTC, merged